# Clippy configuration for Bar Minimal Tools
# https://doc.rust-lang.org/clippy/configuration.html

# MSRV (Minimum Supported Rust Version)
msrv = "1.77.0"

# Thresholds
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 10
too-many-lines-threshold = 200

# Disable some pedantic checks that are too strict for Windows APIs
avoid-breaking-exported-api = false
